# Nombre de la acción (puedes poner lo que quieras)
name: Construir y Publicar Imagen Docker

# Cuándo debe ejecutarse este robot
on:
  push:
    # Solo cuando se suba código a la rama "vizcaino"
    branches: [ "vizcaino" ]

# Qué trabajos debe hacer
jobs:
  build-and-push:
    # El robot usará una máquina virtual con Ubuntu (Linux)
    runs-on: ubuntu-latest
    
    # IMPORTANTE: Dale permisos al robot para escribir en tus "Packages"
    permissions:
      contents: read
      packages: write

    steps:
      # 1. El robot "descarga" tu código (app.py, Dockerfile, etc.)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. El robot "inicia sesión" en el registro de paquetes de GitHub
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # Esto es "lalysita"
          password: ${{ secrets.GITHUB_TOKEN }} # Esto es un token mágico que GitHub le da

      # 3. El robot construye tu imagen y la sube
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # Le dice dónde está tu Dockerfile (en la raíz '.')
          context: .
          # Le decimos que SÍ la suba (push)
          push: true
          # El nombre y la versión EXACTA que te pide tu rúbrica
          tags: ghcr.io/${{ github.repository_owner }}/nathalyvizcaino:1.0.1

      - name: Debug - Listar archivos
        run: |
          echo "Directorio actual:"
          pwd
          echo "Archivos encontrados:"
          ls -R

      - name: pruebas de ssh con el servidor
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST  }}
          port: ${{ secrets.VPS_SSH_PORT  }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD  }}
          script: | 
            echo " Conexion exitosa desde GitHub Actions"
            pwd
            date
            whoami
            hostname
            uptime

      - name: pasar el stack.yml al servidor
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST  }}
          port: ${{ secrets.VPS_SSH_PORT  }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD  }}
          source: "stack.yml"
          target: "/home/${{  secrets.VPS_USER  }}/automatizar"
        
      - name: deploy del servidor
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST  }}
          port: ${{ secrets.VPS_SSH_PORT  }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD  }}
          script: |
            echo "deloyando los servicio"

            cd ~/AUTOMATIZAR
            
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u Lalysita --password-stdin
            docker pull ghcr.io/lalysita/nathalyvizcaino:1.0.1

            # Borrar el stack SIEMPRE (si no existe no falla)
            docker stack rm doraemon || true

            # Timpo de espera hasta que bajen los servicios
            sleep 40

            docker stack deploy --with-registry-auth -c stack.yml doraemon

            sleep 30
            # Ver los servicios
            docker ps
